version: "3.9"

services:
    # psql:
    #     image: postgres:12.13-alpine
    #     container_name: psql
    #     restart: always
    #     ports:
    #         - "5432:5432"
    #     environment:
    #         - POSTGRES_NAME=postgres
    #         - POSTGRES_USER=postgres
    #         - POSTGRES_PASSWORD=postgres
    #         #POSTGRES_DB: "postgres"
    #         #POSTGRES_USER: "jiho"
    #         #POSTGRES_PASSWORD: "1q2w3e4r"
    #     volumes:
    #         - ./data/db:/var/lib/postgresql/data

    backend:
        build: .
        #image: test
        container_name: backend
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        # environment:
        #     - POSTGRES_NAME=postgres
        #     - POSTGRES_USER=postgres
        #     - POSTGRES_PASSWORD=postgres
        
        # depends_on:
        #     - psql    